baseURL = "https://jiwonkkang.github.io/"
languageCode = "zh-cn"
title = "MeiK's blog"
theme = "github-style"
googleAnalytics = "G-RHFSNZ7DGH"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "JiwonKkang"
  description = "In solitude, where we are least alone."
  github = "JiwonKkang"
  facebook = "JiwonKkang"
  twitter = "JiwonKkang"
  linkedin = "JiwonKkang"
  instagram = "JiwonKkang"
  tumblr = "JiwonKkang"
  email = "kangji149@naver.com"
  url = "https://jiwonkkang.github.io"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "Korea"
  userStatusEmoji = "ğŸ˜€"
  enableGitalk = true
    
  [params.gitalk]
    clientID = "5a1c911a3bb5ff14fe5e" # Your client ID
    clientSecret = "8586a43d9a15967e4760ef333ef31eab72c6d3ea" # Your client secret
    repo = "jiwonkkang.github.io" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "JiwonKKang" # æ‚¨çš„GitHub ID
    admin = "JiwonKKang" # æ‚¨çš„GitHub ID
    id = "kangji149" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
  [[params.links]]
    title = "Link"
    href = "https://github.com/meik2333"
  [[params.links]]
    title = "Link2"
    href = "https://meik2333.com"
    icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
